namespace CryptoCurrency;

public class CryptocurrencyConfig
{
    public enum CryptocurrencyName
    {
        Bitcoin,
        Litecoin,
        Namecoin,	
        Peercoin,	
        Dogecoin,	
        Gridcoin,
        Primecoin,	
        Ripple,
        Nxt,
        Auroracoin,
        Dash,
        Neo,
        MazaCoin,
        Monero,
        Titcoin,
        Verge,
        Stellar,
        Vertcoin,
        Ethereum,
        EthereumClassic,
        Nano,
        Tether,
        Firo,
        Zcash,
        BitcoinCash,
        Eosdotio,
        Cardano,
        Tron,
        AmbaCoin,
        NervosNetwork,
        Algorand,
        Avalanche,
        ShibaInu,
        Polkadot,
        DeSo,
        SafeMoon
    }
    
    public Dictionary<CryptocurrencyName, string> CryptocurrencyNameMap => new()
    {
        { CryptocurrencyName.Bitcoin, nameof(CryptocurrencyName.Bitcoin) },
        { CryptocurrencyName.Litecoin, nameof(CryptocurrencyName.Litecoin) },
        { CryptocurrencyName.Namecoin, nameof(CryptocurrencyName.Namecoin) },
        { CryptocurrencyName.Peercoin, nameof(CryptocurrencyName.Peercoin) },
        { CryptocurrencyName.Dogecoin, nameof(CryptocurrencyName.Dogecoin) },
        { CryptocurrencyName.Gridcoin, nameof(CryptocurrencyName.Gridcoin) },
        { CryptocurrencyName.Primecoin, nameof(CryptocurrencyName.Primecoin) },
        { CryptocurrencyName.Ripple, nameof(CryptocurrencyName.Ripple) },
        { CryptocurrencyName.Nxt, nameof(CryptocurrencyName.Nxt) },
        { CryptocurrencyName.Auroracoin, nameof(CryptocurrencyName.Auroracoin) },
        { CryptocurrencyName.Dash, nameof(CryptocurrencyName.Dash) },
        { CryptocurrencyName.Neo, nameof(CryptocurrencyName.Neo) },
        { CryptocurrencyName.MazaCoin, nameof(CryptocurrencyName.MazaCoin) },
        { CryptocurrencyName.Monero, nameof(CryptocurrencyName.Monero) },
        { CryptocurrencyName.Titcoin, nameof(CryptocurrencyName.Titcoin) },
        { CryptocurrencyName.Verge, nameof(CryptocurrencyName.Verge) },
        { CryptocurrencyName.Stellar, nameof(CryptocurrencyName.Stellar) },
        { CryptocurrencyName.Vertcoin, nameof(CryptocurrencyName.Vertcoin) },
        { CryptocurrencyName.Ethereum, nameof(CryptocurrencyName.Ethereum) },
        { CryptocurrencyName.EthereumClassic, "Ethereum Classic" },
        { CryptocurrencyName.Nano, nameof(CryptocurrencyName.Nano) },
        { CryptocurrencyName.Tether, nameof(CryptocurrencyName.Tether) },
        { CryptocurrencyName.Firo, nameof(CryptocurrencyName.Firo) },
        { CryptocurrencyName.Zcash, nameof(CryptocurrencyName.Zcash) },
        { CryptocurrencyName.BitcoinCash, "Bitcoin Cash" },
        { CryptocurrencyName.Eosdotio, "EOS.IO" },
        { CryptocurrencyName.Cardano, nameof(CryptocurrencyName.Cardano) },
        { CryptocurrencyName.Tron, nameof(CryptocurrencyName.Tron) },
        { CryptocurrencyName.AmbaCoin, nameof(CryptocurrencyName.AmbaCoin) },
        { CryptocurrencyName.NervosNetwork, "Nervos Network" },
        { CryptocurrencyName.Algorand, nameof(CryptocurrencyName.Algorand) },
        { CryptocurrencyName.Avalanche, nameof(CryptocurrencyName.Avalanche) },
        { CryptocurrencyName.ShibaInu, "Shiba Inu" },
        { CryptocurrencyName.Polkadot, nameof(CryptocurrencyName.Polkadot) },
        { CryptocurrencyName.DeSo, nameof(CryptocurrencyName.DeSo) },
        { CryptocurrencyName.SafeMoon, nameof(CryptocurrencyName.SafeMoon) }
    };
}